### ISSUE TITLE
support more options

### ISSUE THREAD

**Issue by tcurdt** [zhhz/gulp-ga#2]
Similar to `awestruct` it should support further options:
- anonymizeIp
- demographics
- linkAttribution
- bounceTime

https://github.com/awestruct/awestruct/blob/master/lib/awestruct/extensions/google_analytics.rb#L61

        html += %Q(ga('create', '#{options[:account]}', 'auto');\n)
        html += %Q(ga('send', 'pageview');\n)
        html += %Q(ga('set', 'anonymizeIp', true);\n) if options[:anonymizeIp]
        html += %Q(ga('require', 'displayfeatures');\n) if options[:demographics]
        html += %Q(ga('require', 'linkid', 'linkid.js');\n) if options[:linkAttribution]
        html += %Q(setTimeout("ga('send', 'event', 'read', '#{options[:bounceTime]} seconds')", #{options[:bounceTime]}000);\n) if options[:bounceTime]

**Comment by zhhz** [comment]
Done! Added those four options. Please update your package.json to 0.0.3. Let me know if you have any questions. Thanks for the link.

**Comment by tcurdt** [comment]
Wow! That was quick :) Thanks!
