### ISSUE TITLE
sendPageView isn't added

### ISSUE THREAD

**Issue by amitaibu** [zhhz/gulp-ga#5]
According to https://github.com/zhhz/gulp-ga/commit/5bd3b0aeb66dc9707159fbd69a844f5264fdb0a6 we should be able to do `ga{sendPageView: true }`, however it seems that the string is not added.

**Comment by zhhz** [comment]
It should be fixed, please update the version to v0.0.7. Thank you for reporting it.

**Comment by amitaibu** [comment]
:+1:
